Controllers/RfidCodiCaptEmbarqueController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using OfficeOpenXml;
using test_lester02.Models;

namespace test_lester02.Controllers
{
    public class RfidCodiCaptEmbarqueController : Controller
    {
        private readonly ExamenContext _context;

        public RfidCodiCaptEmbarqueController(ExamenContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult GenerarReporte(string startDate, string endDate, string agrupar)
        {
            
            DateTime startDateTime = DateTime.Parse(startDate);
            DateTime endDateTime = string.IsNullOrEmpty(endDate)
                    ? DateTime.Today.AddDays(1).AddMilliseconds(-1)
                    : DateTime.Parse(endDate).AddDays(1).AddMilliseconds(-1);
            List<string> headersList = new List<string>();

            switch (agrupar)
            {
                case "agruparAcronimo":
                        var report = ConsultaAgrupada(startDateTime, endDateTime);

                        headersList.Add("Acronimo");
                        headersList.Add("Viaje");
                        headersList.Add("Cantidad");

                        ViewBag.Headers = headersList;
                        ViewBag.Report = report;
                    break;
                case "agruparViaje":
                        report = ConsultaAgrupadaNoViaje(startDateTime, endDateTime);

                        headersList.Add("Viaje");
                        headersList.Add("Cantidad");
                        headersList.Add("Fecha");

                        ViewBag.Headers = headersList;
                        ViewBag.Report = report;
                    break;
                case "sinAgrupar":
                        report = test(startDateTime, endDateTime);

                        headersList.Add("RFID");
                        headersList.Add("Acrónimo");
                        headersList.Add("Hora de lectura");

                        ViewBag.Headers = headersList;
                        ViewBag.Report = report;
                    break;
            }

            ViewBag.StartDateTime = startDateTime;
            ViewBag.EndDateTime = endDateTime;
            ViewBag.Agrupar = agrupar;

            return View();


        }

        public List<Object> test(DateTime startDate, DateTime endDate)
        {
            var report = _context.TblRfidCodiCaptEmbarques
               .Where(r => r.FechaLectura >= startDate && r.FechaLectura <= endDate)
               .Select(r => new { r.Codebar, r.Acronimo, r.FechaLectura })
               .ToList<Object>();
            return report;
        }

        public List<Object> ConsultaAgrupada(DateTime startDate, DateTime endDate)
        {
            var report = _context.TblRfidCodiCaptEmbarques
                        .Where(r => r.FechaLectura >= startDate && r.FechaLectura <= endDate)
                        .GroupBy(r => new { r.Acronimo, r.Viaje})
                        .Select(g => new
                        {
                            Acronimo = g.Key.Acronimo,
                            Viaje = g.Key.Viaje,
                            Cantidad = g.Count()
                        })
                        .ToList<Object>();
            return report;
        }

        public List<Object> ConsultaAgrupadaNoViaje(DateTime startDate, DateTime endDate)
        {
            var report = _context.TblRfidCodiCaptEmbarques
                        .Where(r => r.FechaLectura >= startDate && r.FechaLectura <= endDate)
                        .GroupBy(r => r.Viaje )
                        .Select(g => new
                        {
                            Viaje = g.Key,
                            Fecha = g.Min(r => r.FechaLectura),
                            Cantidad = g.Count()
                        })
                        .ToList<Object>();
            return report;
        }

        [HttpPost]
        public IActionResult GenerarReporteExcel(string startDate, string endDate)
        {
            DateTime startDateTime = DateTime.Parse(startDate);
            DateTime endDateTime = string.IsNullOrEmpty(endDate)
                    ? DateTime.Today.AddDays(1).AddMilliseconds(-1)
                    : DateTime.Parse(endDate).AddDays(1).AddMilliseconds(-1);

            var report = test(startDateTime, endDateTime);

            //Crear archivo de excel
            ExcelPackage.LicenseContext = LicenseContext.NonCommercial;
            ExcelPackage excelPackage = new ExcelPackage();
            ExcelWorksheet worksheet = excelPackage.Workbook.Worksheets.Add("report");

            //Agregar encabezados
            worksheet.Cells[1, 1].Value = "RFID";
            worksheet.Cells[1, 2].Value = "Acronimo";
            worksheet.Cells[1, 3].Value = "Hora de lectura";

            //Agregar datos
            int row = 2;
            foreach (var item in report)
            {
                var properties = item.GetType().GetProperties();
                worksheet.Cells[row, 1].Value = properties.First(p => p.Name == "Codebar").GetValue(item);
                worksheet.Cells[row, 2].Value = properties.First(p => p.Name == "Acronimo").GetValue(item);
                worksheet.Cells[row, 3].Value = properties.First(p => p.Name == "FechaLectura").GetValue(item);
                row++;
            }

            //Guardar archivo
            MemoryStream stream = new MemoryStream();
            excelPackage.SaveAs(stream);
            stream.Position = 0;

            //devolver el archivo excel a un archivo descargable
            string fileName = "Report_unitario.xlsx";
            string contentType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";

            return File(stream, contentType, fileName);
        }

        [HttpPost]
        public IActionResult GenerarReporteAgrupadoExcel(string startDate, string endDate)
        {
            DateTime startDateTime = DateTime.Parse(startDate);
            DateTime endDateTime = string.IsNullOrEmpty(endDate)
                    ? DateTime.Today.AddDays(1).AddMilliseconds(-1)
                    : DateTime.Parse(endDate).AddDays(1).AddMilliseconds(-1);

            var report = ConsultaAgrupada(startDateTime, endDateTime);

            //Crear archivo de excel
            ExcelPackage.LicenseContext = LicenseContext.NonCommercial;
            ExcelPackage excelPackage = new ExcelPackage();
            ExcelWorksheet worksheet = excelPackage.Workbook.Worksheets.Add("report");

            //Agregar encabezados
            worksheet.Cells[1, 1].Value = "Acronimo";
            worksheet.Cells[1, 2].Value = "Acronimo";
            worksheet.Cells[1, 3].Value = "Cantidad";

            //Agregar datos
            int row = 2;
            foreach (var item in report)
            {
                var properties = item.GetType().GetProperties();
                worksheet.Cells[row, 1].Value = properties.First(p => p.Name == "Acronimo").GetValue(item);
                worksheet.Cells[row, 2].Value = properties.First(p => p.Name == "Viaje").GetValue(item);
                worksheet.Cells[row, 3].Value = properties.First(p => p.Name == "Cantidad").GetValue(item);
                row++;
            }

            //Guardar archivo
            MemoryStream stream = new MemoryStream();
            excelPackage.SaveAs(stream);
            stream.Position = 0;

            //devolver el archivo excel a un archivo descargable
            string fileName = "Reporte_agrupado.xlsx";
            string contentType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";

            return File(stream, contentType, fileName);
        }

        [HttpPost]
        public IActionResult GenerarReporteAgrupadoNoViajeExcel(string startDate, string endDate)
        {
            DateTime startDateTime = DateTime.Parse(startDate);
            DateTime endDateTime = string.IsNullOrEmpty(endDate)
                    ? DateTime.Today.AddDays(1).AddMilliseconds(-1)
                    : DateTime.Parse(endDate).AddDays(1).AddMilliseconds(-1);

            var report = ConsultaAgrupadaNoViaje(startDateTime, endDateTime);

            //Crear archivo de excel
            ExcelPackage.LicenseContext = LicenseContext.NonCommercial;
            ExcelPackage excelPackage = new ExcelPackage();
            ExcelWorksheet worksheet = excelPackage.Workbook.Worksheets.Add("report");

            //Agregar encabezados
            worksheet.Cells[1, 1].Value = "Viaje";
            worksheet.Cells[1, 2].Value = "Cantidad";
            worksheet.Cells[1, 3].Value = "Fecha";

            //Agregar datos
            int row = 2;
            foreach (var item in report)
            {
                var properties = item.GetType().GetProperties();
                worksheet.Cells[row, 1].Value = properties.First(p => p.Name == "Viaje").GetValue(item);
                worksheet.Cells[row, 2].Value = properties.First(p => p.Name == "Cantidad").GetValue(item);
                worksheet.Cells[row, 3].Value = properties.First(p => p.Name == "Fecha").GetValue(item);
                row++;
            }

            //Guardar archivo
            MemoryStream stream = new MemoryStream();
            excelPackage.SaveAs(stream);
            stream.Position = 0;

            //devolver el archivo excel a un archivo descargable
            string fileName = "Reporte_agrupado_noviaje.xlsx";
            string contentType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";

            return File(stream, contentType, fileName);
        }

    }
}

Views/RfidCodiCaptEmbarque/GenerarReporte.cshtml
@{
    var report = ViewBag.Report as List<dynamic>;
    var headers = ViewBag.Headers as List<string>;
    var agrupar = ViewBag.Agrupar as string;
    string action = "";
    switch (agrupar)
    {
        case "agruparAcronimo":
            action = "GenerarReporteAgrupadoExcel";
            break;
        case "agruparViaje":
            action = "GenerarReporteAgrupadoNoViajeExcel";
            break;
        case "sinAgrupar":
            action = "GenerarReporteExcel";
            break;
    }
}

<div class="container">
    <div class="card">
        <div class="card-body">
            <h2 class="card-title">Resultados del Reporte</h2>

            <form asp-controller="RfidCodiCaptEmbarque" asp-action="@action" method="post">
                <input type="hidden" name="startDate" value="@ViewBag.StartDateTime" />
                <input type="hidden" name="endDate" value="@ViewBag.EndDateTime" />
                <button class="btn btn-primary">Exportar excel</button>
            </form>

            <table class="table">
                <thead>
                    <tr>
                        @foreach(var item in headers){
                            <th>@item</th>
                        }
                    </tr>
                </thead>
                <tbody>
                    @if(report != null){
                        switch(agrupar)
                        {
                            case "agruparAcronimo":
                                foreach (var item in report)
                                {
                                    <tr>
                                        <td>@item.Acronimo</td>
                                        <td>@item.Viaje</td>
                                        <td>@item.Cantidad</td>
                                    </tr>
                                }
                                break;
                            case "agruparViaje":
                                foreach (var item in report)
                                {
                                    <tr>
                                        <td>@item.Viaje</td>
                                        <td>@item.Cantidad</td>
                                        <td>@item.Fecha</td>
                                    </tr>
                                }
                                break;
                            case "sinAgrupar":
                                foreach (var item in report)
                                {
                                    <tr>
                                        <td>@item.Codebar</td>
                                        <td>@item.Acronimo</td>
                                        <td>@item.FechaLectura</td>
                                    </tr>
                                }
                                break;

                        }
                    } else{
                        <tr>
                            <td class="text-center">
                                El resultado es null
                            </td>
                        </tr>
                    }
                    
                </tbody>
            </table>
        </div>
    </div>
</div>

Views/RfidCodiCaptEmbarque/Index.cshtml
@model List<TblRfidCodiCaptEmbarque>


<div class="container">

    <div class="card">
        <div class="card-body">
            <h2 class="card-title">Generar Reporte</h2>

            <form asp-controller="RfidCodiCaptEmbarque" asp-action="GenerarReporte" method="post">
                <div class="row justify-content-between">
                    <div class="col">
                        <label class="form-label" for="startDate">Fecha de Inicio:</label>
                        <input class="form-control" type="date" id="startDate" name="startDate" required />

                    </div>
                    <div class="col">
                        <label class="form-label" for="endDate">Fecha de Fin:</label>
                        <input class="form-control" type="date" id="endDate" name="endDate" />
                    </div>
                    <div class="col">
                        <label class="form-label">¿Agrupar por?</label>
                        <div>
                            <div class="form-check">
                                <input class="form-check-input" type="radio" name="agrupar" id="sinAgrupar" value="sinAgrupar" checked>
                                <label class="form-check-label" for="sinAgrupar">
                                    Sin agrupar
                                </label>
                            </div>
                            <div class="form-check">
                                <input class="form-check-input" type="radio" name="agrupar" id="agruparAcronimo" value="agruparAcronimo">
                                <label class="form-check-label" for="agruparAcronimo">
                                    Agrupado por acronimo y secuencia de viaje
                                </label>
                            </div>
                            <div class="form-check">
                                <input class="form-check-input" type="radio" name="agrupar" id="agruparViaje" value="agruparViaje">
                                <label class="form-check-label" for="agruparViaje">
                                    Agrupado por viaje
                                </label>
                            </div>
                        </div>
                    </div>
                    <div class="col">
                        <label class="form-label" for="btnGenerarReporte">&nbsp;</label>
                        <button class="btn btn-primary" id="btnGenerarReporte">Generar Reporte</button>
                    </div>
                </div>

            </form>
        </div>
    </div>
</div>